{
    "password": "fhqqDMHWFN05.15",
    "options": [
        "xiaoWEI05.15PaintX4.0.6",
        "xiaoWEI05.15PaintX4.0.8",
        "xiaoWEI05.15colorFINALE2.7.4",
        "xiaoWEI05.15colorFINALE2.8.1",
        "xiaoWEI05.15colorFINALE2.9.0",
        "xiaoweicolorfinale2.9.1",
        "xiaoWEI05.15MotionVFX",
        "xiaoWEI05.15NEATVIDEO5.6.5",
        "xiaoWEI05.15NEATVIDEO5.6.5FCPX",
        "xiaoWEI05.15NEATVIDEO5.6.5PR",
        "xiaoWEI05.15NEATVIDEO5.6.5AE"
    ]
}
